---
title: "Phoenix set ground truth"
author: "Kiegan Rice"
output: html_document
---

# Read in data, packages  

```{r}
library(bulletxtrctr)
library(tidyverse)


phoenix_pairwise <- readRDS("../data/phoenix/rfscores_manual.rda")
head(phoenix_pairwise)
```

# Investigate lands - known barrels, find "shift"  

```{r}
phoenix_pairwise %>% filter(land1 == "Gun 1-A9-B1-L1") %>% arrange(desc(rfscore))
phoenix_pairwise %>% filter(land1 == "Gun 1-A9-B2-L1") %>% arrange(desc(rfscore))
phoenix_pairwise %>% filter(land1 == "Gun 1-A9-B3-L2") %>% arrange(desc(rfscore))

#bullet 1 land 1 - bullet 2 land 4??
#bullet 1 land 1 - bullet 3 land 6?? 

phoenix_pairwise %>% filter(land1 == "Gun 1-C8-B1-L1") %>% arrange(desc(rfscore))
phoenix_pairwise %>% filter(land1 == "Gun 1-C8-B2-L2") %>% arrange(desc(rfscore))
phoenix_pairwise %>% filter(land1 == "Gun 1-C8-B3-L1") %>% arrange(desc(rfscore))


#bullet 1 land 1 - bullet 2 land 6 (shift = 5)
#bullet 1 land 1 - bullet 3 land 2 (shift = 1)

phoenix_pairwise %>% filter(land1 == "Gun 1-F6-B1-L1") %>% arrange(desc(rfscore))
#bullet 1 land 1 - bullet 2 land 5 (shift = 4)
#bullet 1 land 1 - bullet 3 land 6 (shift = 5)

phoenix_pairwise %>% filter(land1 == "Gun 1-L5-B1-L1") %>% arrange(desc(rfscore))
phoenix_pairwise %>% filter(land1 == "Gun 1-L5-B2-L1") %>% arrange(desc(rfscore))

#bullet 1 land 1 - bullet 2 land ??
#bullet 1 land 1 - bullet 3 land 1 (shift = 0)

phoenix_pairwise %>% filter(land1 == "Gun 1-M2-B1-L1") %>% arrange(desc(rfscore))
#bullet 1 land 1 - bullet 2 land 2 (shift = 1)
#bullet 1 land 1 - bullet 3 land 5 (shift = 4)

phoenix_pairwise %>% filter(land1 == "Gun 1-P7-B1-L1") %>% arrange(desc(rfscore))
#bullet 1 land 1 - bullet 2 land 1 (shift = 0)
#bullet 1 land 1 - bullet 3 land 6 (shift = 5)

phoenix_pairwise %>% filter(land1 == "Gun 1-R3-B1-L1") %>% arrange(desc(rfscore))
#bullet 1 land 1 - bullet 2 land 1 (shift = 0)
#bullet 1 land 1 - bullet 3 land 2 (shift = 1)

phoenix_pairwise %>% filter(land1 == "Gun 1-U10-B1-L1") %>% arrange(desc(rfscore))
phoenix_pairwise %>% filter(land1 == "Gun 1-U10-B2-L1") %>% arrange(desc(rfscore))

#bullet 1 land 1 - bullet 2 land 3 (shift = 2)
#bullet 1 land 1 - bullet 3 land ??
```



# Investigate lands - unknowns, find matches  

```{r}
phoenix_pairwise %>% filter(land1 == "Unknown 1-B-B1-L1") %>% arrange(desc(rfscore))
#bullet B land 1 - barrel C8 bullet 2 land 2 ? 

phoenix_pairwise %>% filter(land1 == "Unknown 1-E-B1-L1") %>% arrange(desc(rfscore))
#bullet E land 1 - barrel F6

phoenix_pairwise %>% filter(land1 == "Unknown 1-H-B1-L1") %>% arrange(desc(rfscore))
#bullet H land 1 - barrel M2

phoenix_pairwise %>% filter(land1 == "Unknown 1-J-B1-L1") %>% arrange(desc(rfscore))
#bullet J land 1 - barrel P7

phoenix_pairwise %>% filter(land1 == "Unknown 1-K-B1-L1") %>% arrange(desc(rfscore))
#bullet K land 1 - barrel R3

phoenix_pairwise %>% filter(land1 == "Unknown 1-N-B1-L1") %>% arrange(desc(rfscore))
#bullet N land 1 - barrel A9 

phoenix_pairwise %>% filter(land1 == "Unknown 1-Q-B1-L1") %>% arrange(desc(rfscore))
#bullet Q land 1 - ???

phoenix_pairwise %>% filter(land1 == "Unknown 1-T-B1-L1") %>% arrange(desc(rfscore))
#bullet T land 1 - ???

phoenix_pairwise %>% filter(land1 == "Unknown 1-Y-B1-L1") %>% arrange(desc(rfscore))
#bullet Y land 1 - ????



```


## To investigate further:  


```{r}
phoenix_lands <- readRDS("../data/phoenix/phoenix_paper.rda")

```

# Now - the mess that is coding this up.  

```{r}
phoenix_lands <- phoenix_lands %>% 
  mutate(source = as.character(source)) %>%
  mutate(source = purrr::map(source, .f = function(col){
    split1<- strsplit(col, "//")[[1]][2]
    split2 <- strsplit(split1, ".x3p")[[1]][1]
    land <- str_sub(split2, start = -2)
    barrel <- ifelse(str_detect(split2, "Unknown") == T, "Unknown", strsplit(split2, "/")[[1]][1])
    bullet <- ifelse(str_detect(split2, "Gun") == T, 
                     strsplit(split2, "/")[[1]][2], str_sub(split2, start = -6, end = -4))
    bbl <- paste(barrel, bullet, land, sep = "/")
    return(bbl)
  })) %>% 
  separate(source, c("barrel", "bullet", "land"), sep = "/")


phoenix_gt <- phoenix_lands %>% select(barrel, bullet, land) %>% mutate(scan_id = paste(barrel, bullet, land, sep = "-"))
write_csv(phoenix_gt, path = "../data/phoenix/phoenix_gt.csv") 

## manually put in unique ID's for each individual "land". 
```

```{r}
phoenix_gt <- read_csv("../data/phoenix/phoenix_gt.csv")
head(phoenix_gt)

phoenix_mat <- matrix(NA, nrow = nrow(phoenix_gt), ncol = nrow(phoenix_gt))
row.names(phoenix_mat) <- phoenix_gt$scan_id
colnames(phoenix_mat) <- phoenix_gt$scan_id

for (i in 1:nrow(phoenix_mat)){
  for(j in 1:ncol(phoenix_mat)){
    phoenix_mat[i,j] <- ifelse(phoenix_gt$unique_id[i] == phoenix_gt$unique_id[j], "Same Source", "Different Source")
  }
}


phoenix_mat <- as.data.frame(phoenix_mat)
phoenix_mat$land1 <- rownames(phoenix_mat)
phoenix_mat <- phoenix_mat %>% gather(1:198, key = "land2", value = "ground_truth")



phoenix_pairwise <- readRDS("../data/phoenix/rfscores_manual.rda")

phoenix_pairwise <- phoenix_pairwise %>% 
  mutate(land1 = as.character(land1)) %>%
  mutate(land1 = purrr::map_chr(land1, .f = function(col){
    land <- str_sub(col, start = -2)
    barrel <- ifelse(str_detect(col, "Unknown") == T, "Unknown", strsplit(col, "-")[[1]][2])
    bullet <- ifelse(str_detect(col, "Gun") == T, 
                     strsplit(col, "-")[[1]][3], str_sub(col, start = 9, end = 11))
    bbl <- paste(barrel, bullet, land, sep = "/")
    return(bbl)
  })) %>% 
  mutate(land2 = as.character(land2)) %>%
  mutate(land2 = purrr::map_chr(land2, .f = function(col){
    land <- str_sub(col, start = -2)
    barrel <- ifelse(str_detect(col, "Unknown") == T, "Unknown", strsplit(col, "-")[[1]][2])
    bullet <- ifelse(str_detect(col, "Gun") == T, 
                     strsplit(col, "-")[[1]][3], str_sub(col, start = 9, end = 11))
    bbl <- paste(barrel, bullet, land, sep = "/")
    return(bbl)
  })) 

phoenix_mat <- phoenix_mat %>% 
  mutate(land1 = as.character(land1)) %>%
  mutate(land1 = purrr::map_chr(land1, .f = function(col){
    land <- str_sub(col, start = -2)
    barrel <- ifelse(str_detect(col, "Unknown") == T, "Unknown", strsplit(col, "-")[[1]][2])
    bullet <- ifelse(str_detect(col, "Gun") == T, 
                     strsplit(col, "-")[[1]][3], str_sub(col, start = 9, end = 11))
    bbl <- paste(barrel, bullet, land, sep = "/")
    return(bbl)
  })) %>% 
  mutate(land2 = as.character(land2)) %>%
  mutate(land2 = purrr::map_chr(land2, .f = function(col){
    land <- str_sub(col, start = -2)
    barrel <- ifelse(str_detect(col, "Unknown") == T, "Unknown", strsplit(col, "-")[[1]][2])
    bullet <- ifelse(str_detect(col, "Gun") == T, 
                     strsplit(col, "-")[[1]][3], str_sub(col, start = 9, end = 11))
    bbl <- paste(barrel, bullet, land, sep = "/")
    return(bbl)
  })) 

phoenix_results <- full_join(phoenix_pairwise, phoenix_mat)
head(phoenix_results)

phoenix_results$rfscore_manual <- phoenix_results$rfscore
phoenix_results <- phoenix_results %>% select(-rfscore)

saveRDS(phoenix_results, "../data/phoenix/phoenix_results.rda")
```

```{r}
rfscore_roll <- readRDS("../data/phoenix/rfscores_roll.rda")
rfscore_lb <- readRDS("../data/phoenix/rfscores_lb.rda")
rfscore_lf <- readRDS("../data/phoenix/rfscores_lf.rda")
rfscore_bcp <- readRDS("../data/phoenix/rfscores_bcp.rda")


rfscore_roll <- rfscore_roll %>% 
  mutate(land1 = as.character(land1)) %>%
  mutate(land1 = purrr::map_chr(land1, .f = function(col){
    land <- str_sub(col, start = -2)
    barrel <- ifelse(str_detect(col, "Unknown") == T, "Unknown", strsplit(col, "-")[[1]][2])
    bullet <- ifelse(str_detect(col, "Gun") == T, 
                     strsplit(col, "-")[[1]][3], str_sub(col, start = 9, end = 11))
    bbl <- paste(barrel, bullet, land, sep = "/")
    return(bbl)
  })) %>% 
  mutate(land2 = as.character(land2)) %>%
  mutate(land2 = purrr::map_chr(land2, .f = function(col){
    land <- str_sub(col, start = -2)
    barrel <- ifelse(str_detect(col, "Unknown") == T, "Unknown", strsplit(col, "-")[[1]][2])
    bullet <- ifelse(str_detect(col, "Gun") == T, 
                     strsplit(col, "-")[[1]][3], str_sub(col, start = 9, end = 11))
    bbl <- paste(barrel, bullet, land, sep = "/")
    return(bbl)
  }))
rfscore_lb <- rfscore_lb %>% 
  mutate(land1 = as.character(land1)) %>%
  mutate(land1 = purrr::map_chr(land1, .f = function(col){
    land <- str_sub(col, start = -2)
    barrel <- ifelse(str_detect(col, "Unknown") == T, "Unknown", strsplit(col, "-")[[1]][2])
    bullet <- ifelse(str_detect(col, "Gun") == T, 
                     strsplit(col, "-")[[1]][3], str_sub(col, start = 9, end = 11))
    bbl <- paste(barrel, bullet, land, sep = "/")
    return(bbl)
  })) %>% 
  mutate(land2 = as.character(land2)) %>%
  mutate(land2 = purrr::map_chr(land2, .f = function(col){
    land <- str_sub(col, start = -2)
    barrel <- ifelse(str_detect(col, "Unknown") == T, "Unknown", strsplit(col, "-")[[1]][2])
    bullet <- ifelse(str_detect(col, "Gun") == T, 
                     strsplit(col, "-")[[1]][3], str_sub(col, start = 9, end = 11))
    bbl <- paste(barrel, bullet, land, sep = "/")
    return(bbl)
  }))

rfscore_lf <- rfscore_lf %>% 
  mutate(land1 = as.character(land1)) %>%
  mutate(land1 = purrr::map_chr(land1, .f = function(col){
    land <- str_sub(col, start = -2)
    barrel <- ifelse(str_detect(col, "Unknown") == T, "Unknown", strsplit(col, "-")[[1]][2])
    bullet <- ifelse(str_detect(col, "Gun") == T, 
                     strsplit(col, "-")[[1]][3], str_sub(col, start = 9, end = 11))
    bbl <- paste(barrel, bullet, land, sep = "/")
    return(bbl)
  })) %>% 
  mutate(land2 = as.character(land2)) %>%
  mutate(land2 = purrr::map_chr(land2, .f = function(col){
    land <- str_sub(col, start = -2)
    barrel <- ifelse(str_detect(col, "Unknown") == T, "Unknown", strsplit(col, "-")[[1]][2])
    bullet <- ifelse(str_detect(col, "Gun") == T, 
                     strsplit(col, "-")[[1]][3], str_sub(col, start = 9, end = 11))
    bbl <- paste(barrel, bullet, land, sep = "/")
    return(bbl)
  }))

rfscore_bcp <- rfscore_bcp %>% 
  mutate(land1 = as.character(land1)) %>%
  mutate(land1 = purrr::map_chr(land1, .f = function(col){
    land <- str_sub(col, start = -2)
    barrel <- ifelse(str_detect(col, "Unknown") == T, "Unknown", strsplit(col, "-")[[1]][2])
    bullet <- ifelse(str_detect(col, "Gun") == T, 
                     strsplit(col, "-")[[1]][3], str_sub(col, start = 9, end = 11))
    bbl <- paste(barrel, bullet, land, sep = "/")
    return(bbl)
  })) %>% 
  mutate(land2 = as.character(land2)) %>%
  mutate(land2 = purrr::map_chr(land2, .f = function(col){
    land <- str_sub(col, start = -2)
    barrel <- ifelse(str_detect(col, "Unknown") == T, "Unknown", strsplit(col, "-")[[1]][2])
    bullet <- ifelse(str_detect(col, "Gun") == T, 
                     strsplit(col, "-")[[1]][3], str_sub(col, start = 9, end = 11))
    bbl <- paste(barrel, bullet, land, sep = "/")
    return(bbl)
  }))



saveRDS(rfscore_roll, "../data/phoenix/rfscores_roll.rda")
saveRDS(rfscore_lb, "../data/phoenix/rfscores_lb.rda")
saveRDS(rfscore_lf, "../data/phoenix/rfscores_lf.rda")
saveRDS(rfscore_bcp, "../data/phoenix/rfscores_bcp.rda")

```

# Visualize lands to make sure in sequence

```{r}

phoenix_pairwise <- readRDS("../data/phoenix/rfscores_manual.rda")

phoenix_pairwise <- phoenix_pairwise %>% 
  mutate(land1 = as.character(land1)) %>%
  mutate(land1 = purrr::map_chr(land1, .f = function(col){
    land <- str_sub(col, start = -2)
    barrel <- ifelse(str_detect(col, "Unknown") == T, "Unknown", str_sub(col, end = 8))
    bullet <- ifelse(str_detect(col, "Gun") == T, 
                     str_sub(col, start = 10, end = 11), str_sub(col, start = 9, end = 11))
    bbl <- paste(barrel, bullet, land, sep = "/")
    return(bbl)
  })) %>% 
  mutate(land2 = as.character(land2)) %>%
  mutate(land2 = purrr::map_chr(land2, .f = function(col){
    land <- str_sub(col, start = -2)
    barrel <- ifelse(str_detect(col, "Unknown") == T, "Unknown", str_sub(col, end = 8))
    bullet <- ifelse(str_detect(col, "Gun") == T, 
                     str_sub(col, start = 10, end = 11), str_sub(col, start = 9, end = 11))
    bbl <- paste(barrel, bullet, land, sep = "/")
    return(bbl)
  })) #

head(phoenix_pairwise)
phoenix_pairwise <- phoenix_pairwise %>% 
  mutate(barrel_1 = purrr::map_chr(land1, .f = function(col){
    strsplit(col, "/")[[1]][1]}),
    bullet_1 = purrr::map_chr(land1, .f = function(col){
      strsplit(col, "/")[[1]][2]
    }), 
    land_1 = purrr::map_chr(land1, .f = function(col){
      strsplit(col, "/")[[1]][3]
    }), 
    barrel_2 = purrr::map_chr(land2, .f = function(col){
    strsplit(col, "/")[[1]][1]
      }),
    bullet_2 = purrr::map_chr(land2, .f = function(col){
      strsplit(col, "/")[[1]][2]
    }), 
    land_2 = purrr::map_chr(land2, .f = function(col){
      strsplit(col, "/")[[1]][3]
    }) )
head(phoenix_pairwise)
phoenix_pairwise %>%
  filter(str_detect(land1, "Gun 1-A9") == T & str_detect(land2, "Unknown") == T) %>% 
  #filter(str_detect(land1, "Unknown/1-Q") == T) %>% 
  ggplot(aes(x = land2, y = land1, fill = rfscore)) +
  geom_tile() +
  scale_fill_gradient2(low = "grey80", high = "darkorange", 
                       midpoint = .5) +
  facet_wrap(~bullet_2) +
  #xlab("Land A") +
  #ylab("Land B") +
  theme(aspect.ratio = 1, axis.text.x = element_text(angle =10))
```
