---
title: "manual_id_houstontest"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages-and-data, echo = F, message = F, warning = F}
#install.packages("tidyr")
#install.packages("dplyr")
#install.packages("purrr")
#install.packages("ggplot2")
library(tidyr)
library(plyr)
library(dplyr)
library(purrr)
library(ggplot2)

houstontest <- readRDS("//opt/houston-test/houston.rds")
#houstontest[1:6,] # to look at what the first 6 rows look like.  
```

```{r ccdata-define, echo = F}
houstontest <- houstontest %>% mutate(ccdata = purrr::map(ccdata, .f = function(df){
  df %>% group_by(x) %>% dplyr::summarise(y = mean(y, na.rm = T), value = mean(value, na.rm = T))
}))

ccdata <- houstontest$ccdata

```

```{r grooves-define, warning = F}
#devtools::install_github("bulletxtrctr", username = "heike")
library(bulletxtrctr)
grooves <- ccdata %>% purrr::map(.f = function(X) {
  if (is.null(X)) return(NULL) 
  get_grooves_rollapply(x = X$x, value = X$value, return_plot = T)
  })
saveRDS(grooves, file="../data/houston-test/grooves_kr1.rda")
```

```{r manual-groove-id, echo = F}
## code taken from "01-data-processing.Rmd" from Heike

library(shiny)

#if (interactive()) {
shinyApp(
  
  ui = fluidPage(
    selectInput("k","Investigate kth plot:", selected = 1,
                choices=1:length(grooves)),
    textOutput("groovelocations"),
    actionButton("confirm", "Confirm"),
    actionButton("save", "Save"),
    plotOutput("groovePlot", click = "plot_click"),
    verbatimTextOutput("info")
  ),
  
  server = function(input, output, session) {
    output$groovePlot <- renderPlot({
      k <- as.numeric(input$k)
      p <- grooves[[k]]$plot 

      p
    })
    output$groovelocations <- renderText({
      paste("Left Groove: ",grooves[[as.numeric(input$k)]]$groove[1], 
            " Right Groove: ",grooves[[as.numeric(input$k)]]$groove[2])
    })
    observeEvent(input$confirm,{
      cat(str(input$k))
      updateSelectInput(session, "k","Investigate kth plot:", 
                        selected = as.numeric(input$k)+1,
                        choices=1:length(grooves))
    })
    observeEvent(input$save,{
      saveRDS(grooves, file="../data/phoenix/grooves_kr1.rda")
      cat("groove data saved\n")
    })
    
    observeEvent(input$plot_click,{
      k <- as.numeric(input$k)
      xloc <- input$plot_click$x
      
      gr <- grooves[[k]]$groove
      if (abs(gr[1]-xloc) < abs(gr[2]-xloc)) {
        grooves[[k]]$groove[1] <<- xloc
      } else {
        grooves[[k]]$groove[2] <<- xloc
      }
      output$groovePlot <- renderPlot({ 
      k <- as.numeric(input$k)
      p <- grooves[[k]]$plot + 
        geom_vline(xintercept = grooves[[k]]$groove[1], colour="green") +
        geom_vline(xintercept = grooves[[k]]$groove[2], colour="green")
    
      p
      })
  
    })
    output$info <- renderText({
    paste0("x=", input$plot_click$x, "\ny=", input$plot_click$y)
  })

  },

  options = list(height = 500)
)
#}
saveRDS(grooves, file="../data/houston-test/grooves_kr1.rda")

```



```{r}
grooves_kr1 <- readRDS("../data/houston-test/grooves_kr1.rda")
#na_crosscuts <- which(is.na(houston$crosscut)) ## just get rid of these before doing the ShinyApp in the future! 
#grooves <- grooves[-na_crosscuts]
#houston_eval <- houston[-na_crosscuts,]
houstontest_eval <- readRDS("../data/houston-test/houstontest_paper.rda")
houstontest_eval$grooves_kr1 <- grooves_kr1
```


```{r define-left-and-right-groove, echo = F, warning = F, message = F}

houstontest_eval$left_groove_kr1 <- 0
houstontest_eval$right_groove_kr1 <- 0
for (i in 1:nrow(houstontest_eval)){
  houstontest_eval$left_groove_kr1[i] <- houstontest_eval$grooves_kr1[[i]]$groove[1]
  houstontest_eval$right_groove_kr1[i] <- houstontest_eval$grooves_kr1[[i]]$groove[2]
}
head(houstontest_eval)
saveRDS(houstontest_eval, "../data/houston-test/houstontest_eval.rda")
```