---
title: "Untitled"
output: html_document
---

```{r}
hamby44_paper <- readRDS("../data/hamby44/hamby44_paper.rda")

prediction_scores <- function(dataset, method){
  colname <- paste0("grooves_", method)
  new_colname <- paste0("score_left_", method)
  new_colname2 <- paste0("score_right_", method)
  dataset[,new_colname] <- 0
  dataset[,new_colname2] <- 0
  for(i in 1:nrow(dataset)){
    bullet <- dataset[i,]
    left_pred <- bullet[,colname][[1]][[1]]$groove[1]
    left_groove <- as.numeric(bullet[,"left_groove"])
    dat <- bullet$ccdata_w_resid[[1]]
    dat <- dat %>% filter(between(x, min(left_pred, left_groove), max(left_pred, left_groove)))
    dataset[i,new_colname] <- sum(dat$rlo_resid, na.rm = T)
    
    right_pred <- bullet[,colname][[1]][[1]]$groove[2]
    right_groove <- as.numeric(bullet[,"right_groove"])
    dat2 <- bullet$ccdata_w_resid[[1]]
    dat2 <- dat2 %>% filter(between(x, min(right_pred, right_groove), max(right_pred, right_groove)))
    dataset[i, new_colname2] <- sum(dat2$rlo_resid, na.rm = T)
  }
  return(dataset)
}



hamby44_plot <- prediction_scores(hamby44_paper, "rollapply")
hamby44_plot <- prediction_scores(hamby44_plot, "lassobasic")
hamby44_plot <- prediction_scores(hamby44_plot, "lassofull")
hamby44_plot <- prediction_scores(hamby44_plot, "bcp")


```


# plot_scores  


```{r}

plot_scores <- function(dataset, methods = NULL){
  colnames <- c()
  for (i in 1:length(methods)){
    colnames <- c(colnames, paste0("score_left_", methods[i]))
    colnames <- c(colnames, paste0("score_right_", methods[i]))
  }
  plot_df <- dataset %>% ungroup() %>% 
    select(colnames) %>%  
    gather(method, score) %>% 
    mutate(GrooveMethod = unlist(purrr::map(method, .f = function(x){
      strsplit(x, "_")[[1]][3]
        })), GrooveSide = unlist(purrr::map(method, .f = function(x){
      strsplit(x, "_")[[1]][2]
        }))
    )
  plot_df %>% 
    ggplot() + geom_boxplot(aes(x = GrooveSide, y = abs(score), fill = GrooveMethod)) + 
      theme_bw() + labs(x = "Groove Side", y = "Inaccuracy Score")
}

plot_scores(hamby44_plot, methods = c("rollapply", "lassobasic", "lassofull", "bcp"))


```



## plot_scores_zoom

```{r}
head(hamby44_plot)


plot_scores_zoom <- function(dataset, zoom_cutoff, methods = NULL){
  colnames <- c()
  for (i in 1:length(methods)){
    colnames <- c(colnames, paste0("score_left_", methods[i]))
    colnames <- c(colnames, paste0("score_right_", methods[i]))
  }
  plot_df <- dataset %>% ungroup() %>% 
    select(colnames) %>%  
    gather(method, score) %>% 
    mutate(GrooveMethod = unlist(purrr::map(method, .f = function(x){
      strsplit(x, "_")[[1]][3]
        })), GrooveSide = unlist(purrr::map(method, .f = function(x){
      strsplit(x, "_")[[1]][2]
        }))
    ) %>% 
    filter(score < zoom_cutoff)
  plot_df %>% 
    ggplot() + geom_boxplot(aes(x = GrooveSide, y = abs(score), fill = GrooveMethod)) + 
      theme_bw() + labs(x = "Groove Side", y = "Inaccuracy Score")
}

plot_scores_zoom(hamby44_plot, zoom_cutoff = 5000, methods = c("rollapply", "lassobasic", "lassofull", "bcp"))


```



# plot bar charts  
```{r}
dataset <- hamby44_plot
  methods <- c("rollapply", "lassobasic", "lassofull", "bcp")
  colnames <- c()
  for (i in 1:length(methods)){
    colnames <- c(colnames, paste0("score_left_", methods[i]))
    colnames <- c(colnames, paste0("score_right_", methods[i]))
  }
  plot_df <- dataset %>% ungroup() %>% 
    select(colnames) %>%  
    gather(method, score) %>% 
    mutate(GrooveMethod = unlist(purrr::map(method, .f = function(x){
      strsplit(x, "_")[[1]][3]
        })), GrooveSide = unlist(purrr::map(method, .f = function(x){
      strsplit(x, "_")[[1]][2]
        }))
    ) %>% mutate(AccuracyCategory = ifelse(abs(score) < 100, "<100", "100, 1000")) %>% 
    mutate(AccuracyCategory = ifelse(abs(score) >= 1000, ">1000", AccuracyCategory))
  
  plot_df$GrooveLabels <- ifelse(plot_df$GrooveSide=="left", "left shoulder location", "right shoulder location")
  plot_df %>% 
    ggplot() + geom_bar(aes(x = GrooveMethod, fill=factor(AccuracyCategory, levels=c(">1000","100, 1000", "<100"))), position = "stack") + 
      theme_bw() + labs(x = "Groove Method", y = "Number of Lands") + 
    facet_wrap(~GrooveLabels ) + 
    scale_fill_manual(name="Inaccuracy Score", values=c("#E69F00", "#56B4E9", "#009E73"),
                         breaks=c(">1000", "100, 1000", "<100"),
                         labels=c("Greater than 1000", "Between 100 and 1000", "Less than 100")) + 
    scale_x_discrete(name = "Method", breaks = c("rollapply", "lassobasic", "lassofull", "bcp"), 
                     labels = c("Rollapply", "LASSO", "LASSO Interactions", "Bayesian Changepoint"), 
                     limits=c("rollapply","lassobasic","lassofull", "bcp")) + 
    theme(axis.text.x = element_text(angle =10, size = 8))

```



# plot all methods on graph for single land  

```{r}
plot_preds <- function(dataset, bullet_num){
  bullet <- dataset$ccdata[[bullet_num]]
  rollapply_left <- dataset$grooves_rollapply[[bullet_num]]$groove[1]
  rollapply_right <- dataset$grooves_rollapply[[bullet_num]]$groove[2]
  
  lassofull_left <- dataset$grooves_lassofull[[bullet_num]]$groove[1]
  lassofull_right <- dataset$grooves_lassofull[[bullet_num]]$groove[2]
  
  bcp_left <- dataset$grooves_bcp[[bullet_num]]$groove[1]
  bcp_right <- dataset$grooves_bcp[[bullet_num]]$groove[2]
  
  #left <- dataset$left_groove[[bullet_num]]
  #right <- dataset$right_groove[[bullet_num]]
  
  bullet %>% ggplot() + theme_bw() + 
    geom_point(aes(x = x, y = value), size = 0.5) + 
    
    #geom_vline(aes(xintercept = left), lty = 1, colour = "gray31", lwd = 1.3) + 
    #geom_vline(aes(xintercept = right), lty = 1, colour = "gray31", lwd = 1.3) + 
    
    geom_vline(aes(xintercept = rollapply_left), lty = 2, lwd = 1.1, colour = "#E69F00") + 
    geom_vline(aes(xintercept = rollapply_right), lty = 2, lwd = 1.1, colour = "#E69F00") + 
    
    geom_vline(aes(xintercept = lassofull_left), lty = 3, lwd = 1.1, colour = "#009E73") + 
    geom_vline(aes(xintercept = lassofull_right), lty = 3, lwd = 1.1, colour = "#009E73") + 
    
    geom_vline(aes(xintercept = bcp_left), lty = 4, lwd = 1.1, colour = "#56B4E9") + 
    geom_vline(aes(xintercept = bcp_right), lty = 4, lwd = 1.1, colour = "#56B4E9")
    
}
```




## plot within standard deviations  

```{r}

h44_ldf <- data.frame(kr1 = hamby44_paper$left_groove_kr1, kr2 = hamby44_paper$left_groove_kr2, kr3 = hamby44_paper$left_groove_kr3)
h44_ldf$left_manual_sd <- apply(h44_ldf, 1, sd)
h44_ldf$left_manual_mean <- apply(h44_ldf[,1:3], 1, mean)
head(h44_ldf)
h44_ldf <- h44_ldf %>% select(left_manual_sd, left_manual_mean)

hamby44_paper$left_manual_sd <- h44_ldf$left_manual_sd
hamby44_paper$left_manual_mean <- h44_ldf$left_manual_mean



h44_rdf <- data.frame(kr1 = hamby44_paper$right_groove_kr1, kr2 = hamby44_paper$right_groove_kr2, kr3 = hamby44_paper$right_groove_kr3)
h44_rdf$right_manual_sd <- apply(h44_rdf, 1, sd)
h44_rdf$right_manual_mean <- apply(h44_rdf[,1:3], 1, mean)
head(h44_rdf)
h44_rdf <- h44_rdf %>% select(right_manual_sd, right_manual_mean)

hamby44_paper$right_manual_sd <- h44_rdf$right_manual_sd
hamby44_paper$right_manual_mean <- h44_rdf$right_manual_mean

head(hamby44_paper)



prediction_ranges <- function(dataset, method){
  colname <- paste0("grooves_", method)
  new_colname <- paste0("inrange_left_", method)
  new_colname2 <- paste0("inrange_right_", method)
  dataset[,new_colname] <- 0
  dataset[,new_colname2] <- 0
  for(i in 1:nrow(dataset)){
    bullet <- dataset[i,]
    left_pred <- bullet[,colname][[1]][[1]]$groove[1]
    left_groove <- as.numeric(bullet[,"left_manual_mean"])
    left_sd <- as.numeric(bullet[,"left_manual_sd"])
    range5 <- c(left_groove - 5*left_sd, left_groove + 5*left_sd)
    range3 <- c(left_groove - 3*left_sd, left_groove + 3*left_sd)
    
    dataset[i,new_colname] <- ifelse(between(left_pred, range3[1], range3[2]), "Within 3 SD", "Farther than 5 SD")
    dataset[i,new_colname] <- ifelse(between(left_pred, range5[1], range5[2]) & dataset[i,new_colname] != "Within 3 SD", "Within 5 SD", dataset[i,new_colname])
    
    
    right_pred <- bullet[,colname][[1]][[1]]$groove[2]
    right_groove <- as.numeric(bullet[,"right_manual_mean"])
    right_sd <- as.numeric(bullet[,"right_manual_sd"])
    range5 <- c(right_groove - 5*right_sd, right_groove + 5*right_sd)
    range3 <- c(right_groove - 3*right_sd, right_groove + 3*right_sd)
    
    dataset[i,new_colname2] <- ifelse(between(right_pred, range3[1], range3[2]), "Within 3 SD", "Farther than 5 SD")
    dataset[i,new_colname2] <- ifelse(between(right_pred, range5[1], range5[2]) & dataset[i,new_colname2] != "Within 3 SD", "Within 5 SD", dataset[i,new_colname2])
  }
  return(dataset)
}


hamby44_plot_sds <- prediction_ranges(hamby44_paper, method = "rollapply")
hamby44_plot_sds <- prediction_ranges(hamby44_plot_sds, method = "lassobasic")
hamby44_plot_sds <- prediction_ranges(hamby44_plot_sds, method = "lassofull")
hamby44_plot_sds <- prediction_ranges(hamby44_plot_sds, method = "bcp")

head(hamby44_plot_sds)



dataset <- hamby44_plot_sds
  methods <- c("rollapply", "lassobasic", "lassofull", "bcp")
  colnames <- c()
  for (i in 1:length(methods)){
    colnames <- c(colnames, paste0("inrange_left_", methods[i]))
    colnames <- c(colnames, paste0("inrange_right_", methods[i]))
  }
  plot_df <- dataset %>% ungroup() %>% 
    select(colnames) %>%  
    gather(method, inrange) %>% 
    mutate(GrooveMethod = unlist(purrr::map(method, .f = function(x){
      strsplit(x, "_")[[1]][3]
        })), GrooveSide = unlist(purrr::map(method, .f = function(x){
      strsplit(x, "_")[[1]][2]
        }))
    )
  
  plot_df$GrooveLabels <- ifelse(plot_df$GrooveSide=="left", "left shoulder location", "right shoulder location")
  plot_df %>% 
    ggplot() + geom_bar(aes(x = GrooveMethod, fill=factor(inrange, levels=c("Farther than 5 SD","Within 5 SD", "Within 3 SD"))), position = "stack") + 
      theme_bw() + labs(x = "Groove Method", y = "Number of Lands") + 
    facet_wrap(~GrooveLabels ) + 
    scale_fill_manual(name="Accuracy to Manual Predictions", values=c("#E69F00", "#56B4E9", "#009E73"),
                         breaks=c("Farther than 5 SD", "Within 5 SD", "Within 3 SD"),
                         labels=c("More than 5 SD away", "Between 3 and 5 SD away", "Within 3 SD")) + 
    scale_x_discrete(name = "Method", breaks = c("rollapply", "lassobasic", "lassofull", "bcp"), 
                     labels = c("Rollapply", "LASSO", "LASSO Interactions", "Bayesian Changepoint"), 
                     limits=c("rollapply","lassobasic","lassofull", "bcp")) + 
    theme(axis.text.x = element_text(angle =10, size = 8))



```




## PHOENIX 

```{r}
phoenix_paper <- readRDS("../data/phoenix/phoenix_paper.rda")


robust_loess_fit <- function(bullet, iter){
  n <- nrow(bullet)
  weights <- rep(1, n)
  fit <- loess(value_std~x, data = bullet, span = 1)
  bullet$fit <- predict(fit, newdata = bullet)
  bullet$resid <- bullet$value_std - bullet$fit
  i <- 1
  while(i < iter){
    mar <- median(abs(bullet$resid), na.rm = T)
    bullet$bisq <- pmax(1 - (bullet$resid/(6*mar))^2, 0)^2
    weights <- ifelse(bullet$resid > 0 , bullet$bisq, 1)
    fit <- loess(value_std~x, data = bullet, span = 1, weights = weights)
    bullet$fit <- predict(fit, newdata = bullet)
    bullet$resid <- bullet$value_std - bullet$fit
    i <- i+1
  }
  return(fit)
}
  

phoenix_eval <- phoenix_eval %>% mutate(ccdata_w_resid = purrr::map(ccdata, .f = function(land){
  check_min <- min(land$value[!is.na(land$value)])
  land <- land %>% mutate(value_std = value - check_min) 
  rlo_fit <- robust_loess_fit(bullet = land, iter = 20)
  #robust_loess_fit <- locfit.robust(value_std~x, data = land, alpha = 1, kern = "tcub")
  land$rlo_pred <- predict(rlo_fit, newdata = land)
  
  land$rlo_absresid <- with(land, abs(value_std-rlo_pred))
  land$rlo_resid <- with(land, value_std-rlo_pred)
  return(land)
}))



prediction_scores <- function(dataset, method){
  colname <- paste0("grooves_", method)
  new_colname <- paste0("score_left_", method)
  new_colname2 <- paste0("score_right_", method)
  dataset[,new_colname] <- 0
  dataset[,new_colname2] <- 0
  for(i in 1:nrow(dataset)){
    bullet <- dataset[i,]
    left_pred <- bullet[,colname][[1]]$groove[1]
    left_groove <- as.numeric(bullet[,"left_groove"])
    dat <- bullet$ccdata_w_resid[[1]]
    dat <- dat %>% filter(between(x, min(left_pred, left_groove), max(left_pred, left_groove)))
    dataset[i,new_colname] <- sum(dat$rlo_resid, na.rm = T)
    
    right_pred <- bullet[,colname][[1]]$groove[2]
    right_groove <- as.numeric(bullet[,"right_groove"])
    dat2 <- bullet$ccdata_w_resid[[1]]
    dat2 <- dat2 %>% filter(between(x, min(right_pred, right_groove), max(right_pred, right_groove)))
    dataset[i, new_colname2] <- sum(dat2$rlo_resid, na.rm = T)
  }
  return(dataset)
}



phoenix_plot <- prediction_scores(phoenix_paper, "rollapply")
phoenix_plot <- prediction_scores(phoenix_plot, "lassobasic")
phoenix_plot <- prediction_scores(phoenix_plot, "lassofull")
phoenix_plot <- prediction_scores(phoenix_plot, "bcp")

```


## plot_scores  
```{r}
plot_scores <- function(dataset, methods = NULL){
  colnames <- c()
  for (i in 1:length(methods)){
    colnames <- c(colnames, paste0("score_left_", methods[i]))
    colnames <- c(colnames, paste0("score_right_", methods[i]))
  }
  plot_df <- dataset %>% ungroup() %>% 
    select(colnames) %>%  
    gather(method, score) %>% 
    mutate(GrooveMethod = unlist(purrr::map(method, .f = function(x){
      strsplit(x, "_")[[1]][3]
        })), GrooveSide = unlist(purrr::map(method, .f = function(x){
      strsplit(x, "_")[[1]][2]
        }))
    )
  plot_df %>% 
    ggplot() + geom_boxplot(aes(x = GrooveSide, y = abs(score), fill = GrooveMethod)) + 
      theme_bw() + labs(x = "Groove Side", y = "Inaccuracy Score")
}

plot_scores(phoenix_plot, methods = c("rollapply", "lassobasic", "lassofull", "bcp"))

```


## plot_scores_zoom  

```{r}
head(phoenix_plot)


plot_scores_zoom <- function(dataset, zoom_cutoff, methods = NULL){
  colnames <- c()
  for (i in 1:length(methods)){
    colnames <- c(colnames, paste0("score_left_", methods[i]))
    colnames <- c(colnames, paste0("score_right_", methods[i]))
  }
  plot_df <- dataset %>% ungroup() %>% 
    select(colnames) %>%  
    gather(method, score) %>% 
    mutate(GrooveMethod = unlist(purrr::map(method, .f = function(x){
      strsplit(x, "_")[[1]][3]
        })), GrooveSide = unlist(purrr::map(method, .f = function(x){
      strsplit(x, "_")[[1]][2]
        }))
    ) %>% 
    filter(score < zoom_cutoff)
  plot_df %>% 
    ggplot() + geom_boxplot(aes(x = GrooveSide, y = abs(score), fill = GrooveMethod)) + 
      theme_bw() + labs(x = "Groove Side", y = "Inaccuracy Score")
}

plot_scores_zoom(phoenix_plot, zoom_cutoff = 5000, methods = c("rollapply", "lassobasic", "lassofull", "bcp"))


```


## bar chart  

```{r}
dataset <- phoenix_plot
  methods <- c("rollapply", "lassobasic", "lassofull", "bcp")
  colnames <- c()
  for (i in 1:length(methods)){
    colnames <- c(colnames, paste0("score_left_", methods[i]))
    colnames <- c(colnames, paste0("score_right_", methods[i]))
  }
  plot_df <- dataset %>% ungroup() %>% 
    select(colnames) %>%  
    gather(method, score) %>% 
    mutate(GrooveMethod = unlist(purrr::map(method, .f = function(x){
      strsplit(x, "_")[[1]][3]
        })), GrooveSide = unlist(purrr::map(method, .f = function(x){
      strsplit(x, "_")[[1]][2]
        }))
    ) %>% mutate(AccuracyCategory = ifelse(abs(score) < 100, "<100", "100, 1000")) %>% 
    mutate(AccuracyCategory = ifelse(abs(score) >= 1000, ">1000", AccuracyCategory))
  
  plot_df$GrooveLabels <- ifelse(plot_df$GrooveSide=="left", "left shoulder location", "right shoulder location")
  plot_df %>% 
    ggplot() + geom_bar(aes(x = GrooveMethod, fill=factor(AccuracyCategory, levels=c(">1000","100, 1000", "<100"))), position = "stack") + 
      theme_bw() + labs(x = "Groove Method", y = "Number of Lands") + 
    facet_wrap(~GrooveLabels ) + 
    scale_fill_manual(name="Inaccuracy Score", values=c("#E69F00", "#56B4E9", "#009E73"),
                         breaks=c(">1000", "100, 1000", "<100"),
                         labels=c("Greater than 1000", "Between 100 and 1000", "Less than 100")) + 
    scale_x_discrete(name = "Method", breaks = c("rollapply", "lassobasic", "lassofull", "bcp"), 
                     labels = c("Rollapply", "LASSO", "LASSO Interactions", "Bayesian Changepoint"), 
                     limits=c("rollapply","lassobasic","lassofull", "bcp")) + 
    theme(axis.text.x = element_text(angle =10, size = 8))

```


## plot all preds on single land  

```{r}
plot_preds <- function(dataset, bullet_num){
  bullet <- dataset$ccdata[[bullet_num]]
  rollapply_left <- dataset$grooves_rollapply[[bullet_num]]$groove[1]
  rollapply_right <- dataset$grooves_rollapply[[bullet_num]]$groove[2]
  
  lassofull_left <- dataset$grooves_lassofull[[bullet_num]]$groove[1]
  lassofull_right <- dataset$grooves_lassofull[[bullet_num]]$groove[2]
  
  bcp_left <- dataset$grooves_bcp[[bullet_num]]$groove[1]
  bcp_right <- dataset$grooves_bcp[[bullet_num]]$groove[2]
  
  left <- dataset$left_groove[[bullet_num]]
  right <- dataset$right_groove[[bullet_num]]
  
  bullet %>% ggplot() + theme_bw() + 
    geom_point(aes(x = x, y = value), size = 0.5) + 
    
    geom_vline(aes(xintercept = left), lty = 1, colour = "gray31", lwd = 1.3) + 
    geom_vline(aes(xintercept = right), lty = 1, colour = "gray31", lwd = 1.3) + 
    
    geom_vline(aes(xintercept = rollapply_left), lty = 2, lwd = 1.1, colour = "#E69F00") + 
    geom_vline(aes(xintercept = rollapply_right), lty = 2, lwd = 1.1, colour = "#E69F00") + 
    
    geom_vline(aes(xintercept = lassofull_left), lty = 3, lwd = 1.1, colour = "#009E73") + 
    geom_vline(aes(xintercept = lassofull_right), lty = 3, lwd = 1.1, colour = "#009E73") + 
    
    geom_vline(aes(xintercept = bcp_left), lty = 4, lwd = 1.1, colour = "#56B4E9") + 
    geom_vline(aes(xintercept = bcp_right), lty = 4, lwd = 1.1, colour = "#56B4E9")
    
}
```



## plot within standard deviations  


```{r}

pho_ldf <- data.frame(kr1 = phoenix_paper$left_groove_kr1, kr2 = phoenix_paper$left_groove_kr2, kr3 = phoenix_paper$left_groove_kr3)
pho_ldf$left_manual_sd <- apply(pho_ldf, 1, sd)
pho_ldf$left_manual_mean <- apply(pho_ldf[,1:3], 1, mean)
head(pho_ldf)
pho_ldf <- pho_ldf %>% select(left_manual_sd, left_manual_mean)

phoenix_paper$left_manual_sd <- pho_ldf$left_manual_sd
phoenix_paper$left_manual_mean <- pho_ldf$left_manual_mean



pho_rdf <- data.frame(kr1 = phoenix_paper$right_groove_kr1, kr2 = phoenix_paper$right_groove_kr2, kr3 = phoenix_paper$right_groove_kr3)
pho_rdf$right_manual_sd <- apply(pho_rdf, 1, sd)
pho_rdf$right_manual_mean <- apply(pho_rdf[,1:3], 1, mean)
head(pho_rdf)
pho_rdf <- pho_rdf %>% select(right_manual_sd, right_manual_mean)

phoenix_paper$right_manual_sd <- pho_rdf$right_manual_sd
phoenix_paper$right_manual_mean <- pho_rdf$right_manual_mean

head(phoenix_paper)



prediction_ranges_phoenix <- function(dataset, method){
  colname <- paste0("grooves_", method)
  new_colname <- paste0("inrange_left_", method)
  new_colname2 <- paste0("inrange_right_", method)
  dataset[,new_colname] <- 0
  dataset[,new_colname2] <- 0
  for(i in 1:nrow(dataset)){
    bullet <- dataset[i,]
    left_pred <- bullet[,colname][[1]]$groove[1]
    left_groove <- as.numeric(bullet[,"left_manual_mean"])
    left_sd <- as.numeric(bullet[,"left_manual_sd"])
    range5 <- c(left_groove - 5*left_sd, left_groove + 5*left_sd)
    range3 <- c(left_groove - 3*left_sd, left_groove + 3*left_sd)
    
    dataset[i,new_colname] <- ifelse(between(left_pred, range3[1], range3[2]), "Within 3 SD", "Farther than 5 SD")
    dataset[i,new_colname] <- ifelse(between(left_pred, range5[1], range5[2]) & dataset[i,new_colname] != "Within 3 SD", "Within 5 SD", dataset[i,new_colname])
    
    
    right_pred <- bullet[,colname][[1]]$groove[2]
    right_groove <- as.numeric(bullet[,"right_manual_mean"])
    right_sd <- as.numeric(bullet[,"right_manual_sd"])
    range5 <- c(right_groove - 5*right_sd, right_groove + 5*right_sd)
    range3 <- c(right_groove - 3*right_sd, right_groove + 3*right_sd)
    
    dataset[i,new_colname2] <- ifelse(between(right_pred, range3[1], range3[2]), "Within 3 SD", "Farther than 5 SD")
    dataset[i,new_colname2] <- ifelse(between(right_pred, range5[1], range5[2]) & dataset[i,new_colname2] != "Within 3 SD", "Within 5 SD", dataset[i,new_colname2])
  }
  return(dataset)
}


phoenix_plot_sds <- prediction_ranges_phoenix(phoenix_paper, method = "rollapply")
phoenix_plot_sds <- prediction_ranges_phoenix(phoenix_plot_sds, method = "lassobasic")
phoenix_plot_sds <- prediction_ranges_phoenix(phoenix_plot_sds, method = "lassofull")
phoenix_plot_sds <- prediction_ranges_phoenix(phoenix_plot_sds, method = "bcp")

head(phoenix_plot_sds)



dataset <- phoenix_plot_sds
  methods <- c("rollapply", "lassobasic", "lassofull", "bcp")
  colnames <- c()
  for (i in 1:length(methods)){
    colnames <- c(colnames, paste0("inrange_left_", methods[i]))
    colnames <- c(colnames, paste0("inrange_right_", methods[i]))
  }
  plot_df <- dataset %>% ungroup() %>% 
    select(colnames) %>%  
    gather(method, inrange) %>% 
    mutate(GrooveMethod = unlist(purrr::map(method, .f = function(x){
      strsplit(x, "_")[[1]][3]
        })), GrooveSide = unlist(purrr::map(method, .f = function(x){
      strsplit(x, "_")[[1]][2]
        }))
    )
  
  plot_df$GrooveLabels <- ifelse(plot_df$GrooveSide=="left", "left shoulder location", "right shoulder location")
  plot_df %>% 
    ggplot() + geom_bar(aes(x = GrooveMethod, fill=factor(inrange, levels=c("Farther than 5 SD","Within 5 SD", "Within 3 SD"))), position = "stack") + 
      theme_bw() + labs(x = "Groove Method", y = "Number of Lands") + 
    facet_wrap(~GrooveLabels ) + 
    scale_fill_manual(name="Accuracy to Manual Predictions", values=c("#E69F00", "#56B4E9", "#009E73"),
                         breaks=c("Farther than 5 SD", "Within 5 SD", "Within 3 SD"),
                         labels=c("More than 5 SD away", "Between 3 and 5 SD away", "Within 3 SD")) + 
    scale_x_discrete(name = "Method", breaks = c("rollapply", "lassobasic", "lassofull", "bcp"), 
                     labels = c("Rollapply", "LASSO", "LASSO Interactions", "Bayesian Changepoint"), 
                     limits=c("rollapply","lassobasic","lassofull", "bcp")) + 
    theme(axis.text.x = element_text(angle =10, size = 8))



```


