---
title: "Grooves Documentation"
output: html_document
---


## get_grooves_rollapply function  
How does the get_grooves_rollapply function work?  

1. The function begins by saving the `bullet` data frame into the object `original_bullet`. This means that `bullet` can be manipulated, but we still maintain the original structure and data in `original_bullet` for plotting.  


2. If a the `mean_left` and `mean_right` parameters have values, that means the user has supplied an average location of the left groove or right groove for that particular land of the bullet. If that is the case, the function identifies the relevant indices for the average left groove and right groove locations. It also takes a `mean_window` parameter which allows the user to specify how large of a window around this average value to keep when the user applies the rest of the algorithm. Subject to still being within the range of indices of the original `bullet` data frame, this `mean_window` is added and subtracted from the average value, and the `bullet` data frame is updated to only include the rows corresponding to the indices in the two windows - around the left groove and right groove. This has the advantage of reducing the amount of data the algorithm needs to smooth and compare in order to identify the grooves.  

3. Moving forward, the `bullet$value` object - either reduced using the average locations or the full original bullet - is filled in with the `na.fill` function. This function, using the argument "extend", fills in missing values in the following way: 
    - If there are missing values on the "left" of the data (indices starting at row 1), it fills in by repeating the leftmost non-NA value. 
    - If there are missing values on the "right" of the data (indices ending at the final row), it fills in by repeating the rightmost non-NA value.  
    - If there are missing values on the interior of the data, it fills in by using linear interpolation.  

4. Once there is a height value for each index, the function next applies a rolling average to the filled in data. This is done using the `rollapply` function and taking the mean of each window. By default, `rollapply` replaces the center value of the window with the resulting value from whichever function is passed to it (here, the mean). The parameter `smoothfactor`, which the user can specify, determines the width of this window. There is a `partial` parameter in `rollapply` which allows the `FUN` to be applied even when not all of the indices of the window are in the observed range of data. Here, this is set to the default (`FALSE`), so each time smoothing is applied to the object, the first $\lfloor\frac{s}{2}\rfloor$ and the last $\lfloor\frac{s}{2}\rfloor$ values will not have a calculated value ($s$ is the width whose value is passed to `smoothfactor`). Smoothing is applied a second time, meaning that we end up with $4\times\lfloor\frac{s}{2}\rfloor$ fewer observations. This could potentially present an issue if the groove happens to be very close to the edge of the crosscut (either to the very left or very right). However, if the user supplies a very wide smoothing window, that could result in a pretty significant loss of information on the ends of the bullet crosscut. That parameter should also be set with caution in order to avoid over-smoothing of the data, which could remove the ability to identify peaks and valleys.  

5. Following the second smoothing of the crosscut, we are left with `smoothed_truefalse`. The `rollapply` function is used once again, now to identify where the peak of the groove is. Instead of taking a rolling average, a window of size 3 is used to find indices where the middle value - the $2^{nd}$ index in the window - is the maximum. That is, it locates the value $i$ such that $y_i > y_{i+1}$ and $y_i > y_{i-1}$. Once all of these $i$ locations are found, it takes the first instance of that maximum and sets it to be the `peak_ind` (index of the peak), adding back the missing indices ($2\times\lfloor\frac{s}{2}\rfloor$) so that it will directly translate to the original indices of `bullet$value`.    

6. The next step is to identify the groove. This is done by removing all values up to the peak, then applying the same method of finding the locations where the second value in a window of width three is the minimum. The first location where this happens is noted as the `groove_ind` (index of the groove), after adding back the missing indices that were lost during smoothing.  

7. The same process is followed to find the right groove, but the `rev` function is applied to the vector `smoothed_truefalse` so that the indices are flipped and we are approaching the peak and groove from the right. This results in `peak_ind2` and `groove_ind2` values. If any of these peaks or grooves are not found, the grooves are set to be the first and last indices of the original data.  

8. Finally, the function returns a list: first, the values of the grooves as `groove`, with an adjustment (this is a parameter, `adjust`, which moves the values of the grooves closer to the center of the bullet for a positive value and further away for a negative value). Secondly, there is also a plot of the original data as a line with the located grooves as vertical blue lines.  




```{r}

```