---
title: "A Robust Approach to Automatic Edge Detection in 3D Bullet Land Scans"
author: Kiegan Rice, M.S., Heike Hofmann, Ph.D., Ulrike Genschel, Ph.D. 
output: 
  pdf_document: 
    number_sections: true
---

\section{Background}  

Following the 2009 report by the National Research Council on Identifying the Needs of the Forensic Sciences Community (*cite NRC*)

\section{Data Source}  

The data used in this project are high resolution 3D scans of bullet land engraved areas (LEAs).  

The scanned bullets come from the Hamby 44 set (*cite Hamby study*). They consist of 35 total bullets from a set of 10 consecutively rifled Ruger P85 barrels.  

\section{Methodology}  

Due to the presence of data points that deviate from the overall global structure of the land engraved area's curve, robust methods will need to be applied. Robust methods reduce the influence of these outlying points when attempting to fit a line through the global structure. 

- Write about the lack of true linearity in scans of bullet lands - the physical shape of bullet lands.  
- Address differences in left groove, right groove due to the way the bullet is shot out of the barrel.  
- 



\section{Results}  


\section{Conclusions}  

