---
output: 
  pdf_document:
    fig_caption: true
fontsize: 10pt
geometry: margin=1in 
bibliography: bibliography.bib
---


**Validation Study on Automated Groove Detection Methods in 3D Bullet Land Scans**  

*Kiegan Rice, MS, Ulrike Genschel, PhD, Heike Hofmann, PhD*  


The prevalence of research on the automated comparison of bullet marks has increased in the last several years, particularly following the 2016 PCAST report on the validity of feature-comparison methods in forensic science. The main avenue being pursued in this research area is the use of statistical models applied to high-resolution 3D scans of land engraved areas. An important step in introducing these new automated methods is ensuring accurate data pre-processing techniques.  

Being able to correctly identify between data from land engraved areas (LEAs) and groove engraved areas (GEAs) turns out to be the single most important step in data pre-processing. Dealing with these areas separately is crucial to ensure good model fits in subsequent processing steps. Removal of data from groove engraved areas significantly reduces the amount of noise in the characteristics used in automated comparisons. Failure to correctly identify and remove data from groove engraved areas can lead to misidentification of these characteristics.  

Distinguishing between land and groove engraved areas is a problem at which human vision excels, but it is quite challenging for  automatic procedures due to the nature of the data collected: the bullet curvature presents the main structure in the data, but 
the abrupt change between land and groove engraved areas introduces a competing structure. This overwhelms standard modeling techniques. We have employed pre-processing techniques based on robust statistical methods to distinguish between land and groove engraved areas. 
Techniques from robust statistical methods allow the algorithm to focus on the main structure and separate out elements from the secondary structure of the groove engraved area.

Results from these techniques showed early promise when applied to the closed-set study of the Hamby Set 44 [@Hamby] bullets. The pre-processing methods are evaluated at different levels: in a first step we compare predicted results from the techniques to manually identified groove locations. A second, and maybe more important step is to assess the performance of a method in regards to the prediction accuracy of the automated matching algorithm as described in @Hare1.

We are using closed-set and open-set studies to evaluate the effectiveness and accuracy of the proposed techniques. Results are based on publicly available data from the NIST Ballistics Research Database as well as studies from collaborating forensic laboratories and departments across the United States. This additional validation step tests the proposed method's ability to transfer to different types of bullets and rifling methods and highlights limitations. This litany of validation steps ensures a safe use of the proposed technique in fully automating the process and removing the need for human intervention in the data pre-processing.  

**Educational objectives**: Presentation attendees will understand the proposed pre-processing approach we are taking, as well as see outcomes from automated comparison methods from a variety of validation tests on different bullet types.  

**Impact statement**: Our new groove detection and removal process leads to higher accuracy than currently implemented methods, and reduces error rates in the automated comparison process on a variety of bullet types. 


### References  




